const SHOW_AREA = {
    GENERAL_SETTING: "GENERAL_SETTING",
    ELEMENT_LIST: "ELEMENT_LIST",
    ELEMENT_SETTING: "ELEMENT_SETTING",
    ELEMENT_STYLE: "ELEMENT_STYLE"
}

export const AffiliateContextService = {
    
}
