/*******************************************************************************
 * Copyright 2017 (C) Mediastep Software Inc.
 *
 * Created on : 13/03/2020
 * Author: Quy Luong <quy.luong@mediastep.com>
 *******************************************************************************/
export const LEARNING_COMMON_TAB_ID = {
    PRODUCT: 'tab_cm_product',
    COLLECTION: "tab_cm_collection",
    COLLECTION_SERVICE: "tab_cm_collection_ser",
    PAGE: "tab_cm_page",
    MENU: "tab_cm_menu",
    ONLINE_SHOP: "tab_cm_online_shop",
    ORDER: 'tab_cm_order',
    ANALYTIC: "tab_cm_analytic",
    ANALYTIC_RESERVATION: "tab_cm_analytic_res",
    LAZADA: 'tab_cm_lazada',
    SHOPEE: 'tab_cm_shopee',
    GOMUA: 'tab_cm_gomua',
    CUSTOMER: 'tab_cm_customer',
    ADVANCED: 'tab_cm_advanced',
    CUSTOMER_SEGMENT_1: 'tab_cm_segment1',
    CUSTOMER_SEGMENT_2: 'tab_cm_segment2',
    PROMOTION: 'tab_cm_promotion',
    SETTING: 'tab_cm_setting',
    GOCHAT: 'tab_cm_gochat',
    MARKETING: 'tab_cm_marketing',
    STAFF: 'tab_cm_staff',
    WHOLESALE: 'tab_cm_wholesale',
    SERVICE: 'tab_cm_service',
    RESERVATION: 'tab_cm_reservation',
    THEME_SERVICE: 'tab_cm_theme_service'
}

export const LEARNING_COMMON_STEP_CONTENT_ID = {
    STEP_0001: "step0001",
    STEP_0002: "step0002",
    STEP_0003: "step0003",
    STEP_0004: "step0004",
    STEP_0005: "step0005",
    STEP_0006: "step0006",
    STEP_0007: "step0007",
    STEP_0008: "step0008",
    STEP_0009: "step0009",
    STEP_0010: "step0010",
    STEP_0011: "step0011",
    STEP_0012: "step0012",
    STEP_0013: "step0013",
    STEP_0014: "step0014",
    STEP_0015: "step0015",
    STEP_0016: "step0016",
    STEP_0017: "step0017",
    STEP_0018: "step0018",
    STEP_0019: "step0019",
    STEP_0020: "step0020",
    STEP_0021: "step0021",
    STEP_0022: "step0022",
    STEP_0023: "step0023",
    STEP_0024: "step0024",
}

export const TUTORIAL_VIDEOS = {
    LAZADA: 'https://www.youtube.com/embed/DYnFJf7DHWE',
    SHOPEE: 'https://www.youtube.com/embed/pr7m2JtNHAs',
    PRODUCT: 'https://www.youtube.com/embed/CuA9YJd2Q3o',
    GOMUA: 'https://www.youtube.com/embed/-Nd9Iz0CG4U',
    CUSTOMER_IMPORT: 'https://www.youtube.com/embed/RpCcBSoY8Cw',
    CUSTOMER_EXPORT: 'https://www.youtube.com/embed/WBVX2Lqi7Kc',
    ORDER: 'https://www.youtube.com/embed/IFRLe4UhJsw',
    FREE_TIER_ORDER: 'https://www.youtube.com/embed/XJCv6d0rdQw',
    PRODUCT_ANALYTIC: 'https://www.youtube.com/embed/UDLpMlgJgic',
    ADVANCED: 'https://www.youtube.com/embed/-Nj4oCTF46Q',
    CUSTOMER_SEGMENT_1: 'https://www.youtube.com/embed/CcDzfQ6mLnU',
    CUSTOMER_SEGMENT_2: 'https://www.youtube.com/embed/dIay-ESYvoM',
    PROMOTION: 'https://www.youtube.com/embed/YWQ4MljZFXQ',
    SETTING: 'https://www.youtube.com/embed/fM8qHdwxYWQ',
    GOCHAT: 'https://www.youtube.com/embed/Q4UoKl_rPY0',
    MARKETING_EMAIL: 'https://www.youtube.com/embed/3Ud025ld2po',
    MARKETING_LOYALTY: 'https://www.youtube.com/embed/5x-J41GxcOU',
    MARKETING_NOTIFICATION: 'https://www.youtube.com/embed/z3OpAdgkXjQ',
    STAFF: 'https://www.youtube.com/embed/5GoQk9brfOk',
    WHOLESALE: 'https://www.youtube.com/embed/S70pOgHLokA',
    SERVICE: ' https://www.youtube.com/embed/u60hzZX2Kzc',
    SERVICE_COLLECTION: 'https://www.youtube.com/embed/WfIGn1BKGsQ',
    PRODUCT_COLLECTION: 'https://www.youtube.com/embed/COO0jCXFtXM',
    PAGE: 'https://www.youtube.com/embed/mR5J2Scr2MA',
    MENU: 'https://www.youtube.com/embed/OJ1U2BEZLDc',
    THEME_PRODUCT: 'https://www.youtube.com/embed/KcYXOU3cRzk',
    THEME_SERVICE: 'https://www.youtube.com/embed/uiTMd5zaxFg',
    RESERVATION: 'https://www.youtube.com/embed/NIr1idGVubY',
    RESERVATION_ANALYTIC: 'https://www.youtube.com/embed/kXuK1HF4e6o',
    CREATE_ORDER: 'https://www.youtube.com/embed/yp8lsGUPD0A'
}
