export const LANGUAGES = {

    //==================================================//
    // PACKAGE NAME
    //==================================================//
    package_tier_en: "GOOMNI",
    package_web_en: "GOWEB",
    package_web_product_en: "PRODUCTS",
    package_web_product_service_en: "SERVICES AND PRODUCTS",
    package_app_en: "GOAPP",
    package_app_product_en: "PRODUCTS",
    package_app_product_service_en: "SERVICES AND PRODUCTS",
    package_instore_en: "GOPOS",

    package_tier_vi: "GOOMNI",
    package_web_vi: "GOWEB",
    package_web_product_vi: "SẢN PHẨM",
    package_web_product_service_vi: "DỊCH VỤ VÀ SẢN PHẨM",
    package_app_vi: "GOAPP",
    package_app_product_vi: "SẢN PHẨM",
    package_app_product_service_vi: "DỊCH VỤ VÀ SẢN PHẨM",
    package_instore_vi: "GOPOS",

    //==================================================//
    // TAB NAME COMMON
    //==================================================//
    tab_cm_product_en: "Product",
    tab_cm_collection_en: "Product Collection",
    tab_cm_collection_ser_en: "Service Collection",
    tab_cm_page_en: "Page",
    tab_cm_menu_en: "Menu",
    tab_cm_online_shop_en: "Theme",
    tab_cm_order_en: "Orders",
    tab_cm_analytic_en: "Order Analytics ",
    tab_cm_lazada_en: "Lazada",
    tab_cm_shopee_en: "Shopee",
    tab_cm_gomua_en: "Gomua",
    tab_cm_customer_en: "Customer",
    tab_cm_advanced_en: "Advanced",
    tab_cm_segment1_en: "Customer segment by order",
    tab_cm_segment2_en: "Customer segment by profile",
    tab_cm_promotion_en: "Promotion",
    tab_cm_setting_en: "Setting",
    tab_cm_gochat_en: "GoChat",
    tab_cm_marketing_en: "Marketing",
    tab_cm_staff_en: "Staff",
    tab_cm_wholesale_en: "Wholesale",
    tab_cm_service_en: "Service",
    tab_cm_reservation_en: "Reservation",
    tab_cm_analytic_res_en: "Reservation Analytics",

    tab_cm_product_vi: "Sản phẩm",
    tab_cm_collection_vi: "Bộ sưu tập sản phẩm",
    tab_cm_collection_ser_vi: "Bộ sưu tập dịch vụ",
    tab_cm_page_vi: "Trang",
    tab_cm_menu_vi: "Danh mục",
    tab_cm_online_shop_vi: "Theme",
    tab_cm_order_vi: "Đơn hàng",
    tab_cm_analytic_vi: "Phân tích đơn hàng",
    tab_cm_lazada_vi: "Lazada",
    tab_cm_shopee_vi: "Shopee",
    tab_cm_gomua_vi: "Gomua",
    tab_cm_customer_vi: "Khách hàng",
    tab_cm_advanced_vi: "Nâng cao",
    tab_cm_segment1_vi: "Phân nhóm khách hàng theo đơn hàng",
    tab_cm_segment2_vi: "Phân nhóm khách hàng theo thông tin",
    tab_cm_promotion_vi: "Ưu đãi",
    tab_cm_setting_vi: "Cài đặt",
    tab_cm_gochat_vi: "GoChat",
    tab_cm_marketing_vi: "Tiếp thị",
    tab_cm_staff_vi: "Phân quyền nhân viên",
    tab_cm_wholesale_vi: "Giá sỉ",
    tab_cm_service_vi: "Dịch vụ",
    tab_cm_reservation: "Đặt chỗ",
    tab_cm_analytic_res_vi: "Phân tích đặt chỗ"
}
