export const CommissionTypeEnum = {
    TYPE: {
        APPLIES_TO_ALL_PRODUCTS: 'ALL_PRODUCTS',
        APPLIES_TO_SPECIFIC_COLLECTIONS: 'SPECIFIC_COLLECTIONS',
        APPLIES_TO_SPECIFIC_PRODUCTS: 'SPECIFIC_PRODUCTS'
    }
}
