/*******************************************************************************
 * Copyright 2017 (C) Mediastep Software Inc.
 *
 * Created on : 13/08/2019
 * Author: Quy Luong <quy.luong@mediastep.com>
 *******************************************************************************/
export const DiscountConditionOptionEnum = {
    CUSTOMER_SEGMENT: {
        CUSTOMER_SEGMENT_ALL_CUSTOMERS: 'CUSTOMER_SEGMENT_ALL_CUSTOMERS',
        CUSTOMER_SEGMENT_SPECIFIC_SEGMENT: 'CUSTOMER_SEGMENT_SPECIFIC_SEGMENT'
    },
    APPLIES_TO: {
        APPLIES_TO_ENTIRE_ORDER: 'APPLIES_TO_ENTIRE_ORDER',
        APPLIES_TO_ALL_PRODUCTS: 'APPLIES_TO_ALL_PRODUCTS',
        APPLIES_TO_ALL_SERVICES: 'APPLIES_TO_ALL_SERVICES',
        APPLIES_TO_SPECIFIC_COLLECTIONS: 'APPLIES_TO_SPECIFIC_COLLECTIONS',
        APPLIES_TO_SPECIFIC_PRODUCTS: 'APPLIES_TO_SPECIFIC_PRODUCTS',
        APPLIES_TO_SPECIFIC_SERVICES: 'APPLIES_TO_SPECIFIC_SERVICES'
    },
    MIN_REQUIREMENTS: {
        MIN_REQUIREMENTS_NONE: 'MIN_REQUIREMENTS_NONE',
        MIN_REQUIREMENTS_PURCHASE_AMOUNT: 'MIN_REQUIREMENTS_PURCHASE_AMOUNT',
        MIN_REQUIREMENTS_QUANTITY_OF_ITEMS: 'MIN_REQUIREMENTS_QUANTITY_OF_ITEMS'
    },
    PLATFORMS: {
        PLATFORMS_APP_WEB: 'PLATFORMS_APP_WEB',
        PLATFORMS_WEB_ONLY: 'PLATFORMS_WEB_ONLY',
        PLATFORMS_APP_ONLY: 'PLATFORMS_APP_ONLY',
        PLATFORMS_INSTORE_ONLY: 'PLATFORMS_INSTORE_ONLY',
        PLATFORMS_APP_WEB_INSTORE: 'PLATFORMS_APP_WEB_INSTORE',
        PLATFORMS_APP_INSTORE: 'PLATFORMS_APP_INSTORE',
        PLATFORMS_WEB_INSTORE: 'PLATFORMS_WEB_INSTORE',
        WEB: 'WEB',
        APP: 'APP',
        IN_STORE: 'IN_STORE'
    },
    APPLIES_TO_BRANCH: {
        APPLIES_TO_BRANCH_ALL_BRANCHES: 'APPLIES_TO_BRANCH_ALL_BRANCHES',
        APPLIES_TO_BRANCH_SPECIFIC_BRANCH: 'APPLIES_TO_BRANCH_SPECIFIC_BRANCH'
    }
}
